### ISSUE TITLE
Similar schemas with diferent Java class name

### ISSUE THREAD

**Issue by JuanPalacios** [mojohaus/jaxb2-maven-plugin#46]
Hello,

I have two very similar XML schema to compile in the same java proyect. Even the schemas have the same root element but I customize the class name through:

<xs:appinfo>
      <jaxb:class name="Comunicacion1">
       ....
      </jaxb:class>
</xs:appinfo>

The compiler report an error saying that the first element was found, so I can't generarte all the classes. Thanks in advance

``org.xml.sax.SAXParseException: 'JOB' is already defined
	at com.sun.xml.xsom.impl.parser.ParserContext$1.reportError(ParserContext.java:180)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.reportError(NGCCRuntimeEx.java:175)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.reportError(NGCCRuntimeEx.java:178)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.checkDoubleDefError(NGCCRuntimeEx.java:150)
	at com.sun.xml.xsom.impl.parser.state.Schema.action7(Schema.java:137)
	at com.sun.xml.xsom.impl.parser.state.Schema.onChildCompleted(Schema.java:1172)
	at com.sun.xml.xsom.impl.parser.state.NGCCHandler.revertToParentFromText(NGCCHandler.java:183)
	at com.sun.xml.xsom.impl.parser.state.elementDeclBody.text(elementDeclBody.java:860)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendText(NGCCRuntime.java:433)
	at com.sun.xml.xsom.impl.parser.state.elementDeclBody.text(elementDeclBody.java:984)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendText(NGCCRuntime.java:433)
	at com.sun.xml.xsom.impl.parser.state.NGCCHandler.revertToParentFromText(NGCCHandler.java:184)
	at com.sun.xml.xsom.impl.parser.state.complexType.text(complexType.java:1712)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.processPendingText(NGCCRuntime.java:236)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.endElement(NGCCRuntime.java:312)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(Unknown Source)
	at com.sun.tools.xjc.util.SubtreeCutter.endElement(SubtreeCutter.java:112)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(Unknown Source)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(Unknown Source)
	at com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.endElement(CustomizationContextChecker.java:199)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(Unknown Source)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(Unknown Source)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
	at com.sun.xml.xsom.parser.JAXPParser.parse(JAXPParser.java:100)
	at com.sun.tools.xjc.ModelLoader$2.parse(ModelLoader.java:497)
	at com.sun.tools.xjc.ModelLoader$XMLSchemaParser.parse(ModelLoader.java:269)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity(NGCCRuntimeEx.java:347)
	at com.sun.xml.xsom.impl.parser.ParserContext.parse(ParserContext.java:128)
	at com.sun.xml.xsom.parser.XSOMParser.parse(XSOMParser.java:171)
	at com.sun.tools.xjc.ModelLoader.createXSOMSpeculative(ModelLoader.java:514)
	at com.sun.tools.xjc.ModelLoader.loadXMLSchema(ModelLoader.java:369)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:174)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:119)
	at com.sun.tools.xjc.Driver.run(Driver.java:354)
	at org.codehaus.mojo.jaxb2.javageneration.AbstractJavaGeneratorMojo.performExecution(AbstractJavaGeneratorMojo.java:402)
	at org.codehaus.mojo.jaxb2.AbstractJaxbMojo.execute(AbstractJaxbMojo.java:257)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] file:/C:/ARQ-SDK/vpesjpb/eclipse_workspace/BeanComunicacionesMojoHausPlugin/src/m

**Comment by lennartj** [comment]
This is a SAX parse exception which does not seem to pertain to the Jaxb2-maven-plugin.
