### ISSUE TITLE
<xsd:include> don't work

### ISSUE THREAD

**Issue by sbuisson** [mojohaus/jaxb2-maven-plugin#57]
I have , in my code:

```
  <xsd:include schemaLocation="common.xsd" />
 <xsd:complexType name="complexType.Category" mixed="false">
        <xsd:attribute name="mode" type="simpleType.ImportMode"/>
        <xsd:attribute name="category-id" type="simpleType.Generic.NonEmptyString.256"/>
    </xsd:complexType>
```

and , in common.xsd:
<xs:schema targetNamespace="http://www.w3.org/XML/1998/namespace" xmlns:xs="http://www.w3.org/2001/XMLSchema">

```
    <xs:simpleType name="simpleType.ImportMode">
        <xs:restriction base="xs:string">
            <xs:enumeration value="delete"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>
```

And your plugin don't work:

```
org.xml.sax.SAXParseException; systemId: file:/Users/sbuisson/workspace-mlk/mlk-worker-file-to-sqs/src/main/resources/xsd/pricebook.xsd; lineNumber: 43; columnNumber: 67; src-resolve : Impossible de résoudre le nom 'simpleType.ImportMode' en un composant 'simpleType definition'.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:437)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4162)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4145)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDAbstractTraverser.reportSchemaError(XSDAbstractTraverser.java:721)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDAttributeTraverser.traverseNamedAttr(XSDAttributeTraverser.java:332)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDAttributeTraverser.traverseLocal(XSDAttributeTraverser.java:113)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDAbstractTraverser.traverseAttrsAndAttrGrps(XSDAbstractTraverser.java:615)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.processComplexContent(XSDComplexTypeTraverser.java:1123)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexTypeDecl(XSDComplexTypeTraverser.java:335)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseGlobal(XSDComplexTypeTraverser.java:191)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseGlobalDecl(XSDHandler.java:1888)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(XSDHandler.java:1776)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseNamedElement(XSDElementTraverser.java:405)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseGlobal(XSDElementTraverser.java:242)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseSchemas(XSDHandler.java:1433)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:630)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:617)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:575)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:541)
        at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:255)
        at com.sun.tools.xjc.reader.xmlschema.parser.SchemaConstraintChecker.check(SchemaConstraintChecker.java:111)
        at com.sun.tools.xjc.ModelLoader.loadXMLSchema(ModelLoader.java:360)
        at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:174)
        at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:119)
        at com.sun.tools.xjc.Driver.run(Driver.java:354)
        at org.codehaus.mojo.jaxb2.javageneration.AbstractJavaGeneratorMojo.performExecution(AbstractJavaGeneratorMojo.java:402)
        at org.codehaus.mojo.jaxb2.AbstractJaxbMojo.execute(AbstractJaxbMojo.java:257)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)


```

The plugin work otherwise, and the xsd is labeled as "valid" by Intelliji

**Comment by lennartj** [comment]
We normally use xsd:import, rather than xsd:include within the ITs.
Will device an integration test for import as well.

However, in the meantime you could use the import statement instead.

**Comment by slachiewicz** [comment]
Per the W3C XML Schema specification, <xsd:include> requires both schemas to share the exact same target namespace (or the included schema must have no target namespace). Attempting to <xsd:include> a schema declaring targetNamespace="http://www.w3.org/XML/1998/namespace" into a schema with a different target namespace is invalid XML Schema. For referencing components across differing namespaces, <xsd:import> must be used. Closing as invalid schema.
